[hyper-parameter]
penalty = "l2"
dual = false
tol = 0.0001
C = 1.0
fit_intercept = true
intercept_scaling = 1.0
# class_weight = None
random_state = 0
solver = "lbfgs"
max_iter = 100
verbose = 0
warm_start = false
# n_jobs = None
# l1_ratio = None
